const port = process.env.OPENSHIFT_NODEJS_PORT || process.env.VCAP_APP_PORT || process.env.PORT || process.argv[2] || 8765;
const host = process.env.OPENSHIFT_NODEJS_HOST || process.env.VCAP_APP_HOST || process.env.HOST || 'localhost';
const express = require('express');
const proxy = require('express-http-proxy');
const http = require('http');
const app = express();
const server = http.createServer(app);
const Gun = require('gun');
const gun = Gun({ file: 'data.json', web: server });
app.use(Gun.serve);
app.use(proxy(host + ':8765'));
server.listen(port);
console.log('Server started on port ' + port + ' with /gun');